name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - uses: actions/checkout@v4

    # Set up Node.js environment
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Install Node.js dependencies
    - name: Install dependencies
      run: npm ci

    # Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Run Playwright tests in dev environment
    - name: Run Playwright Tests in dev
      run: npm run test:dev

    # Upload Playwright report as an artifact
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
